### ISSUE TITLE
thread '<unnamed>' panicked at src/multisketch.rs:149:30 etc  running sketchlib dist

### ISSUE THREAD

**Issue by CarmenGenpax** [bacpop/sketchlib.rust#31]
Hi, 

I have been testing the Rust version of Sketchlib and tried to run a distance query for a single sketch file against a database .

The distances calculation fails with multiple errors as below: 

**2024-10-30T13:01:56.206Z INFO  [sketchlib] Calculating all ref vs query distances
0% ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ eta:0s
thread '<unnamed>' panicked at src/multisketch.rs:149:30:
range end index 448 out of range for slice of length 224
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
0% ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ eta:1s
thread '<unnamed>' panicked at src/multisketch.rs:149:30:
range end index 53984224 out of range for slice of length 224
0% ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ eta:1s
thread '<unnamed>' panicked at src/multisketch.rs:149:30:
range end index 67424224 out of range for slice of length 224
0% ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ eta:1s**

I'm running on WSL, I was able to sketch the query sample successfully using sketchlib sketch from sketchlib.rust

**Comment by johnlees** [comment]
Can you share the command you ran? And if applicable the query genome/sketch?

**Comment by CarmenGenpax** [comment]
Sure the command was as in the documentation - against the files from the AllTheBacteria project. My colleague has also tried the same thing independently on his machine in case I did something wrong and he's got the same errors (different genome).


 sketchlib dist -v -k 17 atb_sketchlib_v020 query

Sketch files attached ,

Thanks for the quick response

Carmen



________________________________

**Comment by johnlees** [comment]
May well be a bug in the query code which is less well tested sorry.
@vrbouza could you help us take a look at this one again? Thanks!!

**Comment by CarmenGenpax** [comment]
Thanks Both!

________________________________

**Comment by vrbouza** [comment]
Hi @CarmenGenpax , we didn't receive the data files you were using, could you attach them here in the issue?

Thanks!

**Comment by CarmenGenpax** [comment]
Sorry the issue isn't accepting that type of file. I can't upload them. I was querying the db from allthebacteria.  It was a random assembly from ncbi  sketched using sketchlib.rust as in the instructions. I tried two different assemblies with the same issue.

**Comment by CarmenGenpax** [comment]
Just tested your tigr4 example test file and that gives the same error. I also checked the md5sum for the downloaded database and it matches that stated so the database appears to be ok. 

I ran a dists --subset function for a set of sample and that worked ok. so it appears to only be the query not working.

**Comment by johnlees** [comment]
I suspect a bug in the query mode, which we hadn't properly tested yet

**Comment by vrbouza** [comment]
Yes, I think I've fixed it already. I'll do a couple more checks and create a PR.
